# Generated by Django 5.2.3 on 2025-06-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='objet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', "En cours d'envoi"), ('envoye', 'Envoyée'), ('envoye_partiel', 'Envoyée partiellement'), ('erreur', 'Erreur'), ('planifie', 'Planifiée')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
