# Generated by Django 5.2.3 on 2025-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newsletter_objet_alter_newsletter_statut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='ajouter_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='ajouter_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='couleur_texte',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='contenu_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('planifie', 'Planifié'), ('en_cours', "En cours d'envoi"), ('envoye', 'Envoyé'), ('envoye_partiel', 'Envoyé partiellement'), ('erreur', 'Erreur')], default='brouillon', max_length=20),
        ),
    ]
